# Generated by Django 5.1.7 on 2025-03-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointement',
            new_name='Appointment',
        ),
    ]
